[package]
name = "registrar-bot"
version = "0.1.2"
authors = ["lamafab <42901763+lamafab@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "registrar"
path = "src/lib.rs"

[[bin]]
name = "registrar-bot"
path = "src/bin/main.rs"

[dependencies]
log = { version = "0.4.11", features = ["serde"] }
env_logger = "0.7.1"
tokio = { version = "0.2.22", features = ["macros"] }
futures = "0.3.5"
async-trait = "0.1.40"
tungstenite = "0.11.1"
tokio-tungstenite = "0.11.0"
failure = "0.1.8"
serde = "1.0.116"
serde_json = "1.0.57"
crossbeam = "0.7.3"
futures-channel = "0.3.5"
reqwest = { version = "0.10.8", features = ["json"] }
urlencoding = "1.1.1"
matrix-sdk = { version = "0.1.0", git = "https://github.com/matrix-org/matrix-rust-sdk.git" }
lettre = "0.9.0"
lettre_email = "0.9.4"
imap = "2.3.0"
mailparse = "0.13.0"
actix-web = "3.1.0"
native-tls = "0.2.4"
hmac = "0.9.0"
sha-1 = "0.9.1"
sha2 = "0.9.1"
base58 = "0.1.0"
base64 = "0.12.3"
url = "2.1.1"
rusqlite = ">=0.17.3"
schnorrkel = "0.9.1"
ed25519 = "1.0.2"
rand = "0.7.3"
hex = "0.4.2"
